services:
  - type: web
    name: predicter-metabase
    env: docker
    repo: https://github.com/marian-andre/render-com-metabase.git # optional
    plan: starter # ensure that metabase has at least 2GB of RAM (defaults to starter)
    autoDeploy: false
    region: frankfurt
    envVars:
      - key: MB_DB_CONNECTION_URI
        fromDatabase:
          name: predicter-metabase-database
          property: connectionString
databases:
  - name: predicter-metabase-database
    databaseName: metabasedb
    plan: Basic-256mb
    diskSizeGB: 1
    region: frankfurt
    ipAllowList: [] # only allow internal connections
